<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPUAKYIW2768" name="TestNG Group" tests="62" failures="25" timestamp="2 Nov 2016 11:32:42 GMT" time="1.326" errors="0">
  <testcase name="testDoubleDivNegTest" time="0.185" classname="tests.TestCalculator">
    <failure type="org.testng.TestNGException" message="
The data provider is trying to pass 3 parameters but the method tests.TestCalculator#testDoubleDivNegTest takes 2">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 3 parameters but the method tests.TestCalculator#testDoubleDivNegTest takes 2
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 4 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleDivNegTest -->
  <testcase name="testDoubleCTanPosTest" time="0.001" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [-1.6038519064146899] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [-1.6038519064146899] but found [1.0]
	at tests.TestCalculator.testDoubleCTanPosTest(TestCalculator.java:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleCTanPosTest -->
  <testcase name="testDoubleCTanPosTest" time="0.001" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [2.063135125298919] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [2.063135125298919] but found [1.0]
	at tests.TestCalculator.testDoubleCTanPosTest(TestCalculator.java:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleCTanPosTest -->
  <testcase name="testDoubleCTanPosTest" time="0.002" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [1.0686586782881817] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [1.0686586782881817] but found [1.0]
	at tests.TestCalculator.testDoubleCTanPosTest(TestCalculator.java:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleCTanPosTest -->
  <testcase name="testDoubleCTanPosTest" time="0.002" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [0.8636911544506167] but found [0.999329299739067]">
      <![CDATA[java.lang.AssertionError: expected [0.8636911544506167] but found [0.999329299739067]
	at tests.TestCalculator.testDoubleCTanPosTest(TestCalculator.java:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleCTanPosTest -->
  <testcase name="testDoubleTanPosTest" time="0.0" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [-3.380515006246586] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [-3.380515006246586] but found [1.0]
	at tests.TestCalculator.testDoubleTanPosTest(TestCalculator.java:88)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleTanPosTest -->
  <testcase name="testDoubleTanPosTest" time="0.0" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [1.1578212823495775] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [1.1578212823495775] but found [1.0]
	at tests.TestCalculator.testDoubleTanPosTest(TestCalculator.java:88)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleTanPosTest -->
  <testcase name="testDoubleTanPosTest" time="0.001" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [-2.185039863261519] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [-2.185039863261519] but found [1.0]
	at tests.TestCalculator.testDoubleTanPosTest(TestCalculator.java:88)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleTanPosTest -->
  <testcase name="testDoubleTanPosTest" time="0.0" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [0.3200403893795629] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [0.3200403893795629] but found [1.0]
	at tests.TestCalculator.testDoubleTanPosTest(TestCalculator.java:88)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleTanPosTest -->
  <testcase name="testDoubleCosPosTest" time="0.002" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [-0.9899924966004454] but found [0.1411200080598672]">
      <![CDATA[java.lang.AssertionError: expected [-0.9899924966004454] but found [0.1411200080598672]
	at tests.TestCalculator.testDoubleCosPosTest(TestCalculator.java:110)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleCosPosTest -->
  <testcase name="testDoubleCosPosTest" time="0.005" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [-0.9524129804151563] but found [-0.3048106211022167]">
      <![CDATA[java.lang.AssertionError: expected [-0.9524129804151563] but found [-0.3048106211022167]
	at tests.TestCalculator.testDoubleCosPosTest(TestCalculator.java:110)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleCosPosTest -->
  <testcase name="testDoubleCosPosTest" time="0.009" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [0.8438539587324921] but found [-0.5365729180004349]">
      <![CDATA[java.lang.AssertionError: expected [0.8438539587324921] but found [-0.5365729180004349]
	at tests.TestCalculator.testDoubleCosPosTest(TestCalculator.java:110)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleCosPosTest -->
  <testcase name="testDoubleCosPosTest" time="0.01" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [0.15425144988758405] but found [-0.9880316240928618]">
      <![CDATA[java.lang.AssertionError: expected [0.15425144988758405] but found [-0.9880316240928618]
	at tests.TestCalculator.testDoubleCosPosTest(TestCalculator.java:110)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleCosPosTest -->
  <testcase name="testDoubleCosPosTest" time="0.012" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [-0.5984600690578581] but found [-0.8011526357338304]">
      <![CDATA[java.lang.AssertionError: expected [-0.5984600690578581] but found [-0.8011526357338304]
	at tests.TestCalculator.testDoubleCosPosTest(TestCalculator.java:110)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleCosPosTest -->
  <testcase name="testDoubleCosPosTest" time="0.013" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [1.0] but found [0.0]">
      <![CDATA[java.lang.AssertionError: expected [1.0] but found [0.0]
	at tests.TestCalculator.testDoubleCosPosTest(TestCalculator.java:110)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleCosPosTest -->
  <testcase name="testDoubleTanPosTest" time="0.015" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [0.0] but found [NaN]">
      <![CDATA[java.lang.AssertionError: expected [0.0] but found [NaN]
	at tests.TestCalculator.testDoubleTanPosTest(TestCalculator.java:88)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleTanPosTest -->
  <testcase name="testDoubleTanPosTest" time="0.016" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [-6.4053311966462765] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [-6.4053311966462765] but found [1.0]
	at tests.TestCalculator.testDoubleTanPosTest(TestCalculator.java:88)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleTanPosTest -->
  <testcase name="testDoubleTanPosTest" time="0.02" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [0.8714479827243188] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [0.8714479827243188] but found [1.0]
	at tests.TestCalculator.testDoubleTanPosTest(TestCalculator.java:88)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleTanPosTest -->
  <testcase name="testDoubleTanPosTest" time="0.02" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [-0.29100619138474915] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [-0.29100619138474915] but found [1.0]
	at tests.TestCalculator.testDoubleTanPosTest(TestCalculator.java:88)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleTanPosTest -->
  <testcase name="testDoubleTanPosTest" time="0.022" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [1.3386902103511544] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [1.3386902103511544] but found [1.0]
	at tests.TestCalculator.testDoubleTanPosTest(TestCalculator.java:88)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleTanPosTest -->
  <testcase name="testDoubleCTanPosTest" time="0.034" classname="tests.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected [-3.6778144508505695] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [-3.6778144508505695] but found [1.0]
	at tests.TestCalculator.testDoubleCTanPosTest(TestCalculator.java:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleCTanPosTest -->
  <testcase name="testDoubleSumPosTest" time="1.001" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSumPosTest" time="1.001" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSumPosTest" time="1.002" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSumPosTest" time="1.012" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSumPosTest" time="1.007" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSumPosTest" time="1.008" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSumPosTest" time="1.009" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSinPosTest" time="1.018" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSinPosTest" time="1.015" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSinPosTest" time="1.014" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSinPosTest" time="1.013" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSinPosTest" time="1.013" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSinPosTest" time="1.013" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSumPosTest" time="1.013" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSqrtPosTest" time="1.004" classname="tests.TestCalculator"/>
  <testcase name="testDoubleMultPosTest" time="1.002" classname="tests.TestCalculator"/>
  <testcase name="testDoubleMultPosTest" time="1.002" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSqrtPosTest" time="1.004" classname="tests.TestCalculator"/>
  <testcase name="testDoubleMultPosTest" time="1.003" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSubPosTest" time="1.011" classname="tests.TestCalculator"/>
  <testcase name="testDoubleMultPosTest" time="1.003" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSqrtNegTest" time="1.011" classname="tests.TestCalculator">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.IllegalArgumentException but got org.testng.TestException: 
Method TestCalculator.testDoubleSqrtNegTest(double)[pri:0, instance:tests.TestCalculator@1bc6a36e] should have thrown an exception of class java.lang.IllegalArgumentException">
      <![CDATA[org.testng.TestException: 
Method TestCalculator.testDoubleSqrtNegTest(double)[pri:0, instance:tests.TestCalculator@1bc6a36e] should have thrown an exception of class java.lang.IllegalArgumentException
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Method TestCalculator.testDoubleSqrtNegTest(double)[pri:0, instance:tests.TestCalculator@1bc6a36e] should have thrown an exception of class java.lang.IllegalArgumentException
	... 7 more
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleSqrtNegTest -->
  <testcase name="testDoubleMultPosTest" time="1.003" classname="tests.TestCalculator"/>
  <testcase name="testDoubleMultPosTest" time="1.003" classname="tests.TestCalculator"/>
  <testcase name="testDoubleTanNegTest" time="1.006" classname="tests.TestCalculator">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.IllegalArgumentException but got org.testng.TestException: 
Method TestCalculator.testDoubleTanNegTest(double)[pri:0, instance:tests.TestCalculator@1bc6a36e] should have thrown an exception of class java.lang.IllegalArgumentException">
      <![CDATA[org.testng.TestException: 
Method TestCalculator.testDoubleTanNegTest(double)[pri:0, instance:tests.TestCalculator@1bc6a36e] should have thrown an exception of class java.lang.IllegalArgumentException
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Method TestCalculator.testDoubleTanNegTest(double)[pri:0, instance:tests.TestCalculator@1bc6a36e] should have thrown an exception of class java.lang.IllegalArgumentException
	... 7 more
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleTanNegTest -->
  <testcase name="testDoubleDivPosTest" time="1.01" classname="tests.TestCalculator"/>
  <testcase name="testDoublePowPosTest" time="1.011" classname="tests.TestCalculator"/>
  <testcase name="testDoublePowPosTest" time="1.011" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSubPosTest" time="1.011" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSqrtNegTest" time="1.011" classname="tests.TestCalculator">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.IllegalArgumentException but got org.testng.TestException: 
Method TestCalculator.testDoubleSqrtNegTest(double)[pri:0, instance:tests.TestCalculator@1bc6a36e] should have thrown an exception of class java.lang.IllegalArgumentException">
      <![CDATA[org.testng.TestException: 
Method TestCalculator.testDoubleSqrtNegTest(double)[pri:0, instance:tests.TestCalculator@1bc6a36e] should have thrown an exception of class java.lang.IllegalArgumentException
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Method TestCalculator.testDoubleSqrtNegTest(double)[pri:0, instance:tests.TestCalculator@1bc6a36e] should have thrown an exception of class java.lang.IllegalArgumentException
	... 7 more
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleSqrtNegTest -->
  <testcase name="testDoubleSubPosTest" time="1.011" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSubPosTest" time="1.012" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSubPosTest" time="1.012" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSubPosTest" time="1.012" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSubPosTest" time="1.012" classname="tests.TestCalculator"/>
  <testcase name="testDoubleSumPosTest" time="1.013" classname="tests.TestCalculator"/>
  <testcase name="testDoubleDivPosTest" time="1.024" classname="tests.TestCalculator"/>
  <testcase name="testDoubleCTanNegTest" time="1.023" classname="tests.TestCalculator">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.IllegalArgumentException but got org.testng.TestException: 
Method TestCalculator.testDoubleCTanNegTest(double)[pri:0, instance:tests.TestCalculator@1bc6a36e] should have thrown an exception of class java.lang.IllegalArgumentException">
      <![CDATA[org.testng.TestException: 
Method TestCalculator.testDoubleCTanNegTest(double)[pri:0, instance:tests.TestCalculator@1bc6a36e] should have thrown an exception of class java.lang.IllegalArgumentException
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Method TestCalculator.testDoubleCTanNegTest(double)[pri:0, instance:tests.TestCalculator@1bc6a36e] should have thrown an exception of class java.lang.IllegalArgumentException
	... 7 more
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDoubleCTanNegTest -->
  <testcase name="testDoubleDivPosTest" time="1.041" classname="tests.TestCalculator"/>
  <testcase name="testDoubleDivPosTest" time="1.041" classname="tests.TestCalculator"/>
  <testcase name="testDoubleDivPosTest" time="1.041" classname="tests.TestCalculator"/>
</testsuite> <!-- TestNG Group -->
